apiVersion: v1
kind: Service
metadata:
  name: malaya-service
spec:
  type: LoadBalancer # Exposes IP (or NodePort for Minikube)
  selector:
    app: malaya-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
